project_id = "olpxhavmucrysbdamooy"

[functions.kan-analyze-plant]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.calculate-carbon-footprint]
verify_jwt = true

[functions.generate-plant-notification]
verify_jwt = false

[functions.send-daily-email]
verify_jwt = false
